# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85c2474934a6b5a5fb32e45d2202ce63537c2bb5ff5c03222537e336ddce504fcf3228d619e0f31eb166c7bd89b4ed76fa61bd736ab9267fcfe68b1079ed2f93

test:
  secret_key_base: 37bb2561d63982f1b7516499be8c590dc987982737b1bf0d7740044751d3fc5036325a3e7973c42746c933709f5362873ecb97c9f24d8e34b5db4d4f506788fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
